-- 1. 기존 테이블 정리 (싹 날리기 - 리셋)
drop table if exists film_logs; -- 혹시 남아있다면
drop table if exists photos;
drop table if exists film_rolls;
drop table if exists film_stocks;
drop table if exists gears;

-- 2. 장비(Gear) 테이블 생성 (카메라 & 렌즈)
create table gears (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid default auth.uid() not null,
  type text not null, -- 'camera' or 'lens'
  brand text, -- 'Nikon', 'Canon', 'Leica'
  model text not null -- 'F3', '50mm f1.4'
);

-- 3. 필름 재고(Stock) 테이블 생성 (창고)
create table film_stocks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid default auth.uid() not null,
  name text not null, -- 'Kodak Gold 200'
  expiry_date date, -- 유통기한
  cost_per_roll integer default 0, -- 1롤당 가격
  quantity integer default 1 -- 수량
);

-- 4. 필름통(Roll) 테이블 생성 (사용된 필름 = 앨범)
create table film_rolls (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid default auth.uid() not null,
  name text not null, -- '제주도 여행 (Gold 200)'
  date_start date, -- 촬영일
  
  -- 연결 정보
  stock_id bigint references film_stocks(id), -- 어떤 재고를 썼는지 (선택)
  camera_id bigint references gears(id), -- 어떤 카메라로
  lens_id bigint references gears(id) -- 어떤 렌즈로
);

-- 5. 사진(Photo) 테이블 생성
create table photos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid default auth.uid() not null,
  roll_id bigint references film_rolls(id) on delete cascade not null, -- 어느 필름통 소속
  image_url text not null
);

-- 6. 보안(RLS) 설정 - 내 데이터만 관리
alter table gears enable row level security;
alter table film_stocks enable row level security;
alter table film_rolls enable row level security;
alter table photos enable row level security;

-- 정책 생성 (반복 패턴)
create policy "내 장비" on gears for all using (auth.uid() = user_id);
create policy "내 재고" on film_stocks for all using (auth.uid() = user_id);
create policy "내 필름통" on film_rolls for all using (auth.uid() = user_id);
create policy "내 사진" on photos for all using (auth.uid() = user_id);
