-- 1. 기존 테이블 정리 (싹 날리기)
drop table if exists film_logs;
drop table if exists photos;
drop table if exists film_rolls;

-- 2. 필름통(Roll) 테이블 생성
create table film_rolls (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid default auth.uid() not null, -- 누구 건지
  name text not null, -- "Gold 200", "제주도 여행"
  brand text, -- "Kodak", "Fuji" (선택)
  film_type text, -- "Color Negative", "B&W" (선택)
  iso integer, -- 200, 400 (선택)
  date_start date, -- 촬영 시작일
  date_end date, -- 촬영 종료일
  camera text, -- "Nikon F3" (선택)
  lens text -- "50mm f1.4" (선택)
);

-- 3. 사진(Photo) 테이블 생성
create table photos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid default auth.uid() not null,
  roll_id bigint references film_rolls(id) on delete cascade not null, -- 어느 필름통인지 (필름통 지우면 사진도 삭제)
  image_url text not null, -- 사진 주소
  taken_at timestamp with time zone -- 찍은 시간 (메타데이터 있으면)
);

-- 4. RLS (보안) 설정 - 내 데이터만 보기/쓰기
alter table film_rolls enable row level security;
alter table photos enable row level security;

-- 필름통 정책
create policy "내 필름통 보기" on film_rolls for select using (auth.uid() = user_id);
create policy "내 필름통 만들기" on film_rolls for insert with check (auth.uid() = user_id);
create policy "내 필름통 수정" on film_rolls for update using (auth.uid() = user_id);
create policy "내 필름통 삭제" on film_rolls for delete using (auth.uid() = user_id);

-- 사진 정책
create policy "내 사진 보기" on photos for select using (auth.uid() = user_id);
create policy "내 사진 올리기" on photos for insert with check (auth.uid() = user_id);
create policy "내 사진 삭제" on photos for delete using (auth.uid() = user_id);

-- 5. Storage 정책 (기존 거 재활용하거나 새로 설정)
-- (이미 'scans' 버킷에 대한 정책은 잘 되어 있으니 그대로 둡니다!)
