-- 1. 기존 테이블 정리 (싹 날리기 - 리셋 v3.0)
drop table if exists photos cascade;
drop table if exists film_rolls cascade;
drop table if exists film_stocks cascade;
drop table if exists gears cascade;
drop table if exists film_products cascade; -- 마스터 DB (New!)

-- 2. 장비(Gear) 테이블 생성 (변동 없음)
create table gears (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() not null,
  type text not null, -- 'camera' or 'lens'
  brand text,
  model text not null
);

-- 3. [New!] 필름 제품 마스터 DB (Film Products)
-- 누구나 읽을 수 있고(Public Read), 추가도 가능하게(Insert)
create table film_products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null, -- 'Kodak Gold 200' (고유명)
  brand text, -- 'Kodak'
  type text, -- 'Color Negative'
  iso integer, -- 200
  format text default '135', -- '135', '120'
  is_custom boolean default false, -- 유저가 직접 추가한 건지?
  unique(name, format) -- 중복 방지 (같은 이름, 포맷은 하나만!)
);

-- 4. 재고(Stock) 테이블 (구조 변경!)
create table film_stocks (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() not null,
  
  -- 제품 참조 (이제 이름 대신 ID로 관리!)
  product_id bigint references film_products(id) on delete restrict not null,
  
  expiry_date date, -- 유통기한 (개별 관리)
  cost integer default 0,
  quantity integer default 1
);

-- 5. 필름통(Roll) (구조 변경!)
create table film_rolls (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() not null,
  name text not null, -- 앨범 이름
  date_taken date,
  
  -- 어떤 재고(Stock)를 썼는지 기록
  stock_id bigint references film_stocks(id),
  
  camera_id bigint references gears(id),
  lens_id bigint references gears(id)
);

-- 6. 사진(Photo) (변동 없음)
create table photos (
  id bigint generated by default as identity primary key,
  user_id uuid default auth.uid() not null,
  roll_id bigint references film_rolls(id) on delete cascade not null,
  image_url text not null
);

-- 7. 보안(RLS) 설정
alter table gears enable row level security;
alter table film_stocks enable row level security;
alter table film_rolls enable row level security;
alter table photos enable row level security;
alter table film_products enable row level security; -- 마스터 DB도 보안!

-- 정책 생성
create policy "내 장비" on gears for all using (auth.uid() = user_id);
create policy "내 재고" on film_stocks for all using (auth.uid() = user_id);
create policy "내 필름통" on film_rolls for all using (auth.uid() = user_id);
create policy "내 사진" on photos for all using (auth.uid() = user_id);

-- [중요!] 마스터 DB 정책 (누구나 읽기 가능, 로그인하면 쓰기 가능)
create policy "누구나 필름 조회" on film_products for select using (true);
create policy "로그인하면 필름 추가" on film_products for insert with check (auth.role() = 'authenticated');

-- 8. 초기 데이터(Seed Data) 넣기 (유명한 필름들)
insert into film_products (name, brand, type, iso) values
('Kodak Gold 200', 'Kodak', 'Color Negative', 200),
('Kodak ColorPlus 200', 'Kodak', 'Color Negative', 200),
('Kodak Portra 400', 'Kodak', 'Color Negative', 400),
('Kodak Portra 160', 'Kodak', 'Color Negative', 160),
('Kodak Portra 800', 'Kodak', 'Color Negative', 800),
('Kodak Ektar 100', 'Kodak', 'Color Negative', 100),
('Kodak Ultramax 400', 'Kodak', 'Color Negative', 400),
('Fujifilm C200', 'Fujifilm', 'Color Negative', 200),
('Fujifilm Superia X-TRA 400', 'Fujifilm', 'Color Negative', 400),
('Cinestill 800T', 'Cinestill', 'Color Negative', 800),
('Ilford HP5 Plus 400', 'Ilford', 'B&W', 400),
('Ilford FP4 Plus 125', 'Ilford', 'B&W', 125);
